### ISSUE TITLE
Failed installation on Windows 10

### ISSUE THREAD

**Issue by ralienpp** [cryptocat/cryptocat#171]
This happens on a x86 Windows 10 system. The complete error log of the installer is here: http://pastebin.com/cWqUSCbn

The part that I think is relevant:

```
2016-07-26 13:34:16> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\anycs\AppData\Local\Cryptocat\app-3.2.02\Cryptocat.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
```

Are there any specific troubleshooting steps one could try? Are there any specific flavours of Windows on which Cryptocat is known not to work?

**Comment by kaepora** [comment]
Are you using a 32-bit platform?

**Comment by kaepora** [comment]
Ah, indeed you are. Sadly, Cryptocat is not compatible with 32-bit systems.
